version: '3.8'

services:

  backend:
    container_name: vacation-tracker-backend
    ports:
     - 3000:3000
    environment:
    - NODE_ENV=compose
    build: ./backend
    depends_on:
      database:
        condition: service_healthy


  frontend:
    container_name: vacation-tracker-frontend
    ports:
      - 5173:80
    build: ./frontend

  database:
    container_name: vacation-tracker-database
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=vacation_tracker_db
      - MYSQL_TCP_PORT=3306
    ports: 
      - 3306:3306
    build: ./database
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 60s

  
  io:
    container_name: vacation-tracker-io
    ports:
      - 3003:3003
    build: ./io
    
  localstack: 
   container_name: vacation-tracker-localstack
   ports:
     - 127.0.0.1:4566:4566
     - 127.0.0.1:4510-4559:4510-4559
   image: localstack/localstack




